### ISSUE TITLE
answers my request!

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [wode490390/WorldReset#1]
on worldreset plugin, code on https://github.com/wode490390/NukkitPlugins, so fix it new nukkit version, and please also reset the world in folder worlds to work, i waited new version plugin worldreset..

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/WorldReset/commit/5012a9ef2a1af50242a8147b4eb400f9a53ec13a.
